name: Run Katalon Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: 
      name: Pravins-Windows-Machine

    steps:
      - name: Checkout master branch to $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Get checkout path 
        run: pwd
    
